# Generated by Django 2.2.4 on 2019-08-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190829_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
